### ISSUE TITLE
Unable to download pre-trained model, link cannot be accessed

### ISSUE THREAD

**Issue by dongzhenguo2016** [chongruo/detectron2-ResNeSt#16]
找不到 hangzh.s3.amazonaws.com 的服务器 IP 地址。
Unable to download pre-trained model, link cannot be accessed

**Comment by chongruo** [comment]
Can I ask which model you would like to download?

**Comment by dongzhenguo2016** [comment]
I want to download "object detection cascade rcnn ResNeSt-200"

**Comment by chongruo** [comment]
The link works on my side.

To download that model, you can click on the 'model' and it will start downloading automatically, or run the following command

> wget https://hangzh.s3.amazonaws.com/detectron/faster_cascade_rcnn_ResNeSt_200_FPN_syncbn_range-scale_1x-1be2a87e.pth

**Comment by dongzhenguo2016** [comment]
thanks a lot
