### ISSUE TITLE
Cannot rebulid Detectron2

### ISSUE THREAD

**Issue by dongzhenguo2016** [chongruo/detectron2-ResNeSt#21]
when I execute this code： python -m pip install -e .   
I encountered the following error.
I'm very confused, I found many methods and didn't solve them.
I followed the step by step instructions provided by you.
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=Vk4gID50K03a
错误一：

`(pytorch1.5)  ⚙ hdc@hdc-IBM  /media/hdc/data1/dzc/detectron2-ResNeSt-resnest/detectron2  python -m pip install -e .                                                            [20/05/23| 9:10AM]
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /media/hdc/data1/dzc/detectron2-ResNeSt-resnest/detectron2
`
错误二：运行train_net.py
` from detectron2 import _C
ImportError: cannot import name '_C' from 'detectron2' (/media/hdc/data1/dzc/detectron2-ResNeSt-resnest/detectron2/__init__.py)`

**Comment by chongruo** [comment]
It seems this issue is solved as shown in another tread.
