### ISSUE TITLE
How to draw a detection box and display confidence on the test data

### ISSUE THREAD

**Issue by dongzhenguo2016** [chongruo/detectron2-ResNeSt#23]
Now I can run through the training program. 
Not only do I want to calculate AP and other indicators on the test data set, 
**How do I draw a detection box and display confidence on the test data?**
thanks a lot

**Comment by chongruo** [comment]
please see https://github.com/facebookresearch/detectron2/blob/515c53ad645275dceec15c785c0eb0005bb95b63/detectron2/utils/visualizer.py#L308
