### ISSUE TITLE
how to let AP in  range [0,1]?

### ISSUE THREAD

**Issue by dongzhenguo2016** [chongruo/detectron2-ResNeSt#26]
When I run train_net.py and specify eval_only = True to test and calculate the AP, I find that the calculated AP range is not between [0,1], I feel very strange. Do you know how to calculate the AP value for each range [0,1]? After finding the AP for each category, I can calculate the mAP on the entire test data set. Thank you

**Comment by chongruo** [comment]
https://github.com/facebookresearch/detectron2/issues/1420
