### ISSUE TITLE
## ❓ How to merge this repo with detectron2 master?

### ISSUE THREAD

**Issue by fangchengji** [chongruo/detectron2-ResNeSt#39]
## ❓ How to merge this repo with detectron2 master?

I found the ResNeSt code is all included in resnet.py and splat.py. Besides, this repo uses fvcore==0.1.dev200407, which is different with detectron2 master requirements "fvcore>=0.1.1". Could you tell me what you guys do with fvcore 0.1.dev200407? Could we split this content from fvcore?

**Comment by Cyril9227** [comment]
You have to add the keys used by ResNeSt to the default config, then you can add those 2 files under modeling/backbone and change the __init__

**Comment by fangchengji** [comment]
> You have to add the keys used by ResNeSt to the default config, then you can add those 2 files under modeling/backbone and change the **init**

Thanks for your kindly remind. I have added these config keys. I found it was another merged bug. I tested ResNeSt repo with fvcore==0.1.1, it worked fine. My bad.
