### ISSUE TITLE
How to specify which layers to be trained during transfer learning (finetuning) the network

### ISSUE THREAD

**Issue by NVukobrat** [chongruo/detectron2-ResNeSt#58]
## ❓ How to specify which layers to be trained during transfer learning (finetuning) the network ❓

I would like to specify which layers (beside FC) should be fine-tuned during training on the custom dataset. I saw that there is `C.MODEL.BACKBONE.FREEZE_AT` parameter but I'm not sure if this is the only thing needed to be set in order for this to work.

**Comment by zhanghang1989** [comment]
@chongruo @Jerryzcn Could you look at this question?

**Comment by NVukobrat** [comment]
Hi guys again, any update on this one? :smile: @zhanghang1989 @chongruo @Jerryzcn 

I have additional insights with C.MODEL.BACKBONE.FREEZE_AT parameter. Legend for bellow figure is as follows:

- Red one contains follow configuration:
  - LR: 0.001
  - Steps: 30k
  - Warmup: 10k
  - Gamma: 0.05
  - Gama influenced steps: 20k - 30k
  - RoI minibatch size per image: 512
  - Images per batch: 4
- Blue one configuration:
  - Same as for red one, with difference that FREEZE_AT parameter is set to 2

![image](https://user-images.githubusercontent.com/44512290/102643463-9c9a7980-415f-11eb-9047-a31b7a32df03.png)

From these results (segmentation AP), it seems that the model with FREEZE_AT = 2 is worse than the one with the default FREEZE_AT parameter. Number of image samples I used just to train this model is around 1k atm.

Do you have some insights and explanations about what is actually happening here? :smile:

**Comment by zhanghang1989** [comment]
For longer iterations, end-to-end training has some benefits of improving feature representation. COCO is a large dataset, which even allows training from scratch.

**Comment by NVukobrat** [comment]
Makes sense. I'll need much more data in order to achieve better accuracy with end-to-end training. Do you @zhanghang1989 have a recommendation for the `FREEZE_AT` configuration with 1k, 5k and 10k labeled image samples? I'll probably experiment with a couple of different for specific config parameter, but just want to get additional thoughts on this one.

**Comment by NVukobrat** [comment]
One more update. When I tried FREEZE_AT with 3, 4 and 5 configuration my training stopped with the `following` error:
```bash
raceback (most recent call last):
  File "train_net.py", line 193, in <module>
    args=(args,),
  File "/home/ubuntu/train/resnet/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "train_net.py", line 174, in main
    return trainer.train()
  File "/home/ubuntu/train/resnet/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ubuntu/train/resnet/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/ubuntu/train/resnet/detectron2/engine/train_loop.py", line 217, in run_step
    self._detect_anomaly(losses, loss_dict)
  File "/home/ubuntu/train/resnet/detectron2/engine/train_loop.py", line 240, in _detect_anomaly
    self.iter, loss_dict
FloatingPointError: Loss became infinite or NaN at iteration=0!
loss_dict = {'loss_cls': tensor(nan, device='cuda:0', grad_fn=<NllLossBackward>), 'loss_box_reg': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>), 'loss_mask': tensor(nan, device='cuda:0', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_rpn_cls': tensor(0.7749, device='cuda:0', grad_fn=<MulBackward0>), 'loss_rpn_loc': tensor(0.0063, device='cuda:0', grad_fn=<MulBackward0>)}
```

**Do you know what forces loss to became infinite or Nan from the beginning?** FREEZE_AT with 1 and 2 value works for training.

**Comment by NVukobrat** [comment]
Hi guys, just a quick ping regarding this one :) 
@zhanghang1989

**Comment by zhanghang1989** [comment]
looks like Nan appeared during the training. Try reduce the LR if not training end-to-end.

**Comment by NVukobrat** [comment]
Initially, I used 1e-3 and the following problem appeared with freezing 3 segments (FREEZE_AT = 3). I reduced it to 3e-4 and the problem is still there. Do you have any other information on what can be the cause of the problem?
